name: ClansPlugin
version: '1.0.0'
main: com.develop.clansPlugin.ClansPlugin
api-version: '1.21'
authors: [Simone1212]
commands:
  clan:
    description: Comandi per la gestione del clan
    usage: /clan
softdepend:
  - PlaceholderAPI